version: '3'

services:
    database-patient:
        image: mysql:5.7
        container_name: mysql-docker
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: rootroot
            MYSQL_DATABASE: patientprod
            MYSQL_USER: root
            MYSQL_PASSWORD: rootroot
        volumes:
            - mysqldata:/var/lib/mysql
        networks:
            - ms-net

    patient:
        image: patient
        container_name: patient
        restart: always
        ports:
            - 8081:8081
        networks:
            - ms-net
        depends_on:
            - database-patient

    database-note:
        image: mongo
        container_name: mongo-docker
        restart: always
        ports:
            - 27017:27017
        volumes:
            - mongodata:/data/db
        networks:
            - ms-net

    note:
        image: note
        container_name: note
        restart: always
        ports:
            - 8082:8082
        networks:
            - ms-net
        depends_on:
            - database-note

    rapport:
        image: rapport
        container_name: rapport
        restart: always
        ports:
            - 8080:8080
        networks:
            - ms-net
        depends_on:
            - database-patient
            - patient
            - database-note
            - note

networks:
  ms-net:
      driver: bridge

volumes:
    mysqldata:
    mongodata: